export const API_ERROR_CODES = {
  TIME_CONFLICT: 'TIME_CONFLICT',
  INVALID_TIME_RANGE: 'INVALID_TIME_RANGE',
  INVALID_BLOCK: 'INVALID_BLOCK',
  SERVER_ERROR: 'SERVER_ERROR',
  NETWORK_ERROR: 'NETWORK_ERROR',
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
} as const

export type ApiErrorCode =
  (typeof API_ERROR_CODES)[keyof typeof API_ERROR_CODES]
